// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwPXGzVcJTHRiRpTQ3jj4jIqoK7DxQ7hM',
    appId: '1:562103044871:web:91cdf00941a610b9cf53a2',
    messagingSenderId: '562103044871',
    projectId: 'chat-app-746c0',
    authDomain: 'chat-app-746c0.firebaseapp.com',
    storageBucket: 'chat-app-746c0.firebasestorage.app',
    measurementId: 'G-ZZ4S7X0KY7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-zPVNUexmCrwYyKiSrpLNG65CGWautOo',
    appId: '1:562103044871:android:bedbc5df0d54c3c0cf53a2',
    messagingSenderId: '562103044871',
    projectId: 'chat-app-746c0',
    storageBucket: 'chat-app-746c0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEn5DQhX-wVIzXeqOWUH-cf0LLDxaDz9Y',
    appId: '1:562103044871:ios:1452d4a53ed429a8cf53a2',
    messagingSenderId: '562103044871',
    projectId: 'chat-app-746c0',
    storageBucket: 'chat-app-746c0.firebasestorage.app',
    iosBundleId: 'com.example.youtubeMessengerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEn5DQhX-wVIzXeqOWUH-cf0LLDxaDz9Y',
    appId: '1:562103044871:ios:1452d4a53ed429a8cf53a2',
    messagingSenderId: '562103044871',
    projectId: 'chat-app-746c0',
    storageBucket: 'chat-app-746c0.firebasestorage.app',
    iosBundleId: 'com.example.youtubeMessengerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwPXGzVcJTHRiRpTQ3jj4jIqoK7DxQ7hM',
    appId: '1:562103044871:web:433d5cc1599395a5cf53a2',
    messagingSenderId: '562103044871',
    projectId: 'chat-app-746c0',
    authDomain: 'chat-app-746c0.firebaseapp.com',
    storageBucket: 'chat-app-746c0.firebasestorage.app',
    measurementId: 'G-MYNC9X2FWM',
  );

}